### PR TITLE
feat: a tool to convert json output to SARIF format

### PR DESCRIPTION
**Pull request by justinchuby**
A tool that converts lintrunner json output to SARIF format, compatible with Github code scanning.

https://github.com/justinchuby/lintrunner-adapters/pull/4

Screenshots:

image

image

### CODE REVIEW

**Comment by suo** [comment]
lgtm! Mind including a little test that runs it on an example lintrunner json result?

**Comment by justinchuby** [comment]
Sure! Looks like CI is failing for some reason I couldn't understand

**Comment by suo** [comment]
Looks like this https://github.com/PyO3/maturin-action/issues/99

**Comment by justinchuby** [comment]
I added a test. LMK if you want it done differently!

**Comment by suo** [comment]
can you rebase this change? The test thing should be fixed

**Pull request merged**
